### ISSUE TITLE
Minimum of 20 stars is not being followed

### ISSUE THREAD

**Issue by roniemartinez** [OSSPhilippines/pinoy-made#23]
As 5th in the acceptance criteria:

5. To maintain high quality projects in the list, your project must have at least 20 stars.

I noticed this is not being followed on latest PRs that were merged.

https://github.com/OSSPhilippines/pinoy-made/blob/23189193d4535ff0309aad8ace26b3737e18b751/CONTRIBUTING.md?plain=1#L21

**Comment by warengonzaga** [comment]
Hey @roniemartinez apologies, we'll take a look first with @jofftiquez thanks!

**Comment by jofftiquez** [comment]
@roniemartinez This is negligence on our part. Thank you for filing an issue. We cannot remove the merged project but we will make sure to double check the guidelines moving forward. Thank you again! 💪🏽
